# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-28 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=b'null', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.CharField(default=b'null', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='imglink',
            field=models.CharField(default=b'null', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='published_upto',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=400),
        ),
    ]
